#Note that I've commented out a few blocks: Stone doesn't rot now, and ores don't become mushrooms.
#I like to uncomment these, but... They're DESTRUCTIVE.

mush:
  rottableBlocks:
#    - 1
    - 2
    - 5
    - 19
    - 25
    - 26
    - 35
    - 47
    - 44
    - 53
    - 60
    - 12
    - 97
    - 108
    - 109
  redableBlocks:
    - 6
    - 31
    - 32
    - 38
    - 55
    - 63
  brownableBlocks:
    - 37
    - 32
    - 72
    - 50
    - 51
    - 78
  logBlocks:
    - 17
#    - 14
#    - 15
#    - 16
    - 4
    - 98
  removeBlocks:
    - 13
    - 18
    - 106
  skyBlocks:
    - 99
    - 100
    - 0